### ISSUE TITLE
Terminate services too?

### ISSUE THREAD

**Issue by hfuss** [asobti/kube-monkey#107]
I want to fork this and add destroying entire Service's to kube-monkey. You guys open to the idea?

This would be useful for testing an application's resiliency to a network partition of a particular dependency, for example:
- Your application's Pods talk to another application via a Service
- You're using a ClusterIP Service as a proxy for an external IP
- You have an Ingress or OpenShift Route pointing at a Service

**Comment by asobti** [comment]
That sounds fantastic. I would love to see that

**Comment by brix4dayz** [comment]
Awesome, thanks!

**Comment by brix4dayz** [comment]
I like the idea as that would be really simple, but I don't believe you can rename a Service since there isn't a way to update the hostname/URL simultaneously:
```
$ oc patch svc infinispan -p '{ "metadata": { "name": "infinispanx" } }'
Error from server (BadRequest): the name of the object (infinispanx) does not match the name on the URL (infinispan)
$ kubectl patch svc infinispan -p '{ "metadata": { "name": "infinispanx" } }'
Error from server (BadRequest): the name of the object (infinispanx) does not match the name on the URL (infinispan)
```
Also even if that was allowed, applications might not respect DNS TTL's, and so they could have the ClusterIP of the Service cached and still be able connect.

I was thinking of two ways of "terminating" the Service:
1. Deleting the Service entirely, but saving a copy of its `metadata` and `spec` (and its `Endpoint`'s if it doesn't have a `selector` i.e. for external IP Service's). Then after a random amount of time restoring the Service.
2. Blackholing the Service through a NetworkPolicy for a random period of time. This would be simpler but it might not work for two reasons I can think of:
   i) NetworkPolicy's have to be enabled on OpenShift by an admin, so a dev can't just simply use kube-monkey right away for Service's
   ii) If NetworkPolicy's were already being used, there might be a rule allowing the app to connect to the Service which would trump the deny all policy

So I'm thinking about going with 1. With either solution, we can reuse `kube-monkey/mtbf` for the time between failure, and then I was think of `kube-monkey/mtbr` for "mean time before restoration". I believe those, and the `kube-monkey/enabled` label will be the only ones needed for Service's.

Thoughts?

**Comment by worldtiki** [comment]
Closing as stale
