### ISSUE TITLE
would not it better if dry run superseded schedule_immediate_kill: true

### ISSUE THREAD

**Issue by prageethw** [asobti/kube-monkey#115]
I think at the moment the design is to if schedule_immediate_kill: true to supersede everything else and start killing pods, even dry_run= true, I think it makes a more sense honor dry run as the first option of preference so users can actually experiment without waiting hours. I could have sent a PR proposing a fix, but I'm not much familiar with GO :( my sample config is as below which I used for verification.

 dryRun: true
  runHour: 8
  startHour: 10
  endHour: 16
  blacklistedNamespaces: kube-system
  whitelistedNamespaces:
  timeZone: America/New_York
  debug:
   enabled: true # if you want to enable debugging and see how pods killed immediately set this to true
   schedule_immediate_kill: true

**Comment by asobti** [comment]
The expected behavior if you have both `schedule_immediate_kill` and `dry_run` set to `true`, is that a pod will get scheduled immediately (to aid debugging), but the pod won't actually get killed - kube-monkey will just log that it is killing the pod but not actually kill it (because of `dry_run=true`).

Is that what you were asking @prageethw ?

**Comment by asobti** [comment]
oh wow. ok, that is definitely a bug then. thanks for reporting this

**Comment by asobti** [comment]
Yup, just took a look and it looks like we lost `DryRun` at some point. Will fix this shortly
