### ISSUE TITLE
kube-monkey should respect the termination grace period defined in the pod spec

### ISSUE THREAD

**Issue by asobti** [asobti/kube-monkey#118]
If a `TerminationGracePeriod` is defined in the pod spec and it is larger than the configured grace period, the `TerminationGracePeriod` value should be used

**Comment by jroper** [comment]
Doesn't this defeat the purpose of chaos testing? Failures don't happen gracefully, it's easy to make sure things work when you terminate things gracefully, and things get terminated gracefully all the time (eg during rolling upgrades) so there's no point having an additional service like this testing that. The hard thing is to make things work when things don't terminate gracefully, ie, when they fail, that's why we have chaos testing. I would say that honouring a pods graceful termination period is not failure testing, and undermines all confidence that this tool provides. Failure testing requires a graceful termination period of zero seconds.

**Comment by asobti** [comment]
@jroper Agreed with everything you say. This is tracked by #134

**Comment by asobti** [comment]
@jroper Fixed
