### ISSUE TITLE
Fix Termination time format

### ISSUE THREAD

**Issue by asobti** [asobti/kube-monkey#21]
Currently, termination time is logged to microseconds granularity along with monotonic clock reading.

```
I1109 13:40:56.471721      11 schedule.go:28] 	********** Today's schedule **********
I1109 13:40:56.471749      11 schedule.go:32] 	Deployment		Termination time
I1109 13:40:56.471752      11 schedule.go:33] 	----------		----------------
I1109 13:40:56.471757      11 schedule.go:35] 	hello-world		2017-11-09 13:41:28.4717057 -0800 PST m=+62.093720077
```

See https://golang.org/pkg/time/#Time.String

Suggested fix:

> The returned string is meant for debugging; for a stable serialized representation, use t.MarshalText, t.MarshalBinary, or t.Format with an explicit format string.

**Comment by Spellchaser** [comment]
Do you mean to format it without the granularity?
`glog.V(4).Infof("\t%s\t\t\t%s\n", chaos.Deployment().Name(), chaos.KillAt().Format("01/01/2017 18:42:05 Z0700 UTC"))`

**Comment by Spellchaser** [comment]
Just formatting will output UTC all the time. There's some inconsistencies with how time is printed in the code. In some places, time.In(config.Timezone()) is used while in other places it uses the system local time which usually defaults to UTC. 

This also means issue https://github.com/asobti/kube-monkey/issues/23 is valid since termination times are not printed in the configured timezone.

Happy New Years!

**Comment by Spellchaser** [comment]
I think this issue is resolved!
