### ISSUE TITLE
pod error:  panic: open /usr/local/go/lib/time/zoneinfo.zip: no such file or directory

### ISSUE THREAD

**Issue by pswenson** [asobti/kube-monkey#7]
I tried building and deploying the projecto k8s and I get this error in the pod logs:

```
Starting kube-monkey...
panic: open /usr/local/go/lib/time/zoneinfo.zip: no such file or directory

goroutine 1 [running]:
github.com/asobti/kube-monkey/config.Timezone(0x8)
	/Users/pswens200/dev/gowork/src/github.com/asobti/kube-monkey/config/config.go:77 +0xc5
github.com/asobti/kube-monkey/kubemonkey.Run(0xc420537f68, 0x1)
	/Users/pswens200/dev/gowork/src/github.com/asobti/kube-monkey/kubemonkey/kubemonkey.go:46 +0x5b
main.main()
	/Users/pswens200/dev/gowork/src/github.com/asobti/kube-monkey/main.go:23 +0xa0

```

Any ideas?

**Comment by DavidPesticcio** [comment]
Wherever you are running `kube-monkey` it seems to need the `zoneinfo.zip` file in different places -
this appears to be dependant on your `GOROOT` environment variable setting... this will also be true inside the container - if you're going that far. :-)

Try;
`zip /usr/local/go/lib/time/zoneinfo.zip /usr/share/zoneinfo/`

Substitute `/usr/local/go/lib/time/zoneinfo.zip`, above, according to the `no such file or directory` error.

If you've set the "time_zone" in the `/etc/kube-mokey/config.toml` file, or via the `examples/configmap.yaml`, then make sure you pick a TZ that exists in `/usr/share/zoneinfo/`

HTH

**Comment by valtsi** [comment]
This error is coming from kube-monkey being unable to find the timezone file that [LoadLocation in the Go time package](https://golang.org/pkg/time/#LoadLocation) needs, since the default timezone is "America/Los Angeles". An alternative to creating the timezone file, is to use either the UTC or Local timezones. Those timezones are natively known.

**Comment by asobti** [comment]
kube-monkey could default to the local timezone in case of this error, although I feel that's more dangerous as we really don't want to be scheduling pods to be killed at unexpected times. I think panicking in this situation might be the outcome of least surprise.

**Comment by pswenson** [comment]
changing the Dockerfile to `FROM golang:1.7.5-alpine` seems to resolve the issue.... any reason why this isn't a good solution?

**Comment by asobti** [comment]
@pswenson What timezone are you using that causes that error?

**Comment by MarkDcc** [comment]
You may try to set time_zone="UTC" .

**Comment by YuxiJin-tobeyjin** [comment]
I also get stuck on this problem. Here is one solution for me ,maybe can give some help.
1)use "docker run -itd kube-monkey:v0.1.0 /bin/bash" to run a container
2)use "docker ps" to get its containerid
3)use "docker exec -it {$containerid} bash" to enter into the container
4)run "ll /etc |grep localtime" in the container and you will find it links to someplace:
localtime -> /usr/share/zoneinfo/Etc/UTC
5)In my case ,there is no zoneinfo directory under /usr/share/ in my container.
6)use "docker cp /usr/share/zoneinfo/  {$containerid} :/usr/share/" to copy the directory from host
7)use "docker commit {$containerid} kube-monkey:v0.1.1" to form a new image
The problem is solved for me using this new image "kube-monkey:v0.1.1"
